### ISSUE TITLE
Issues with the Bitnami stack

### ISSUE THREAD

**Issue by zbisho** [ccfiel/s3_backup#5]
Hi, I have my environment installed on AWS via the Bitnami AMI and I'm trying to install this app, I can't seem to get it to install.

are there special instructions for the Bitnami based environment?

Cheers

**Comment by ccfiel** [comment]
@zbisho I do not have any experience in bitnami better use the default installation of erpnext for production 

Chris
https://bai.ph
Bai Web and Mobile Lab

**Comment by zbisho** [comment]
I did that, installed it on a fresh server from the simple install script and then installed the S3 back up as per the instructions,

I then proceeded to setup the backup and got this error msg

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/s3_backup/s3_backup/amazon_s3_backup/doctype/amazon_s3_settings/amazon_s3_settings.py", line 13, in validate
    from boto.s3.connection import S3Connection
ImportError: No module named boto.s3.connection

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/s3_backup/s3_backup/amazon_s3_backup/doctype/amazon_s3_settings/amazon_s3_settings.py", line 13, in validate
    from boto.s3.connection import S3Connection
ImportError: No module named boto.s3.connection

**Comment by zbisho** [comment]
Hi, I still am getting the same error, even though I have Boto installed, any help would be much appreciated

**Comment by phengmeas** [comment]
You can follow this step:
1. Activate env first by running this. source ./frappe-bench/env/bin/activate
2. Install boto
3. filechunkio
3. bench get-app s3_backup https://github.com/bailabs/s3_backup.git
4. bench install-app s3_backup
